### ISSUE TITLE
gulp css --optimize do not minify

### ISSUE THREAD

**Issue by ryuran** [cleverage/garden-starter-kit#58]
The `--optimize`  option seems ignored

NB: Tested with compass builder

Maybe relative to #50

**Comment by stephane-tessier** [comment]
Nope, nothing to do with #50.

The --optimize option works quite fine. The only problem is that if you scss files are not modified, `gulp css` won't modify your destination file either. (unless you delete it manually)

When you run `gulp build`, it first cleans the build repo, so the build will be optimized anyway.

Once you understand that, it's quite a minor problem, but I understand that it's quite confusing :/

I didn't find a way to fix it. (and is it worth it since we migrate to eyeglass?)

**Comment by ryuran** [comment]
I think we must clean css when use `glup css` (not for `gulp live`)

**Comment by stephane-tessier** [comment]
https://github.com/cleverage/garden-starter-kit/pull/60
